import Head from "next/head";
import styled from "styled-components";
import FlexCard from "../components/FlexCard/FlexCard";
import Section from "../components/Section/Section";
import Container from "../components/UI/Container";
import { colors } from "../styles/colors";

// import Image from "next/image";
import styles from "../styles/Home.module.css";

const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  width: 100%;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: ${colors.darkBlue};
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Container
          size="full-width"
          styles={{
            display: "flex",
            justifyContent: "space-evenly",
            color: colors.white,
            gap: "0.5rem",
          }}
        >
          <Section query="trending"></Section>
          <Section query="trending"></Section>

          {/* <Section query="movies"></Section> */}
        </Container>
      </Main>
    </>
  );
}
